terminate called after throwing an instance of 'Xapian::QueryParserError'
Aborted
